### ISSUE TITLE
Travis builds on mac are broken

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#304]
See https://travis-ci.org/deltachat/deltachat-node/builds/526534670

The usual ssl 43 error.

cc @flub @Jikstra

**Comment by flub** [comment]
Yes, except I'm not 100% sure it's the same root cause (the error
reported by libetpan is a bit wide...).  Nevertheless
https://github.com/deltachat/deltachat-node/tree/flub/ci-rpgp is
exploring what it looks like with a fresh libetpan from master (only it
doesn't work yet because everything is hard)
